# Generated by Django 6.0.2 on 2026-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
